apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: union-bank-api
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.union-bank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: union-bank-api
                port:
                  number: 8000
  tls:
    - hosts:
        - api.union-bank.example.com
      secretName: union-bank-tls
