"""
initial_migration.

Revision ID: 808505b8d0f3
Revises:
Create Date: 2026-07-14 20:04:26.224200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "808505b8d0f3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("mobile", sa.String(length=15), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("account_number"),
    )
    op.create_index(
        "idx_accounts_name_number", "accounts", ["name", "account_number"], unique=False
    )
    op.create_index("idx_accounts_status", "accounts", ["is_active", "is_frozen"], unique=False)
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=False)
    op.create_index(op.f("ix_accounts_name"), "accounts", ["name"], unique=False)
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admins_username"), "admins", ["username"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=50), nullable=True),
        sa.Column("details", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor"), "audit_log", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False)
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("first_failed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lockout_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_attempts_key"), "login_attempts", ["key"], unique=True)
    op.create_table(
        "token_versions",
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("account_number"),
    )
    op.create_table(
        "loans",
        sa.Column("loan_id", sa.String(length=20), nullable=False),
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("loan_type", sa.String(length=20), nullable=False),
        sa.Column("principal_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tenure_months", sa.Integer(), nullable=False),
        sa.Column("emi_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remaining_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("application_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approval_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_emi_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purpose", sa.String(length=500), nullable=False),
        sa.Column("admin_notes", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_number"], ["accounts.account_number"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("loan_id"),
    )
    op.create_index("idx_loans_account_status", "loans", ["account_number", "status"], unique=False)
    op.create_index("idx_loans_status_next_emi", "loans", ["status", "next_emi_date"], unique=False)
    op.create_index(op.f("ix_loans_account_number"), "loans", ["account_number"], unique=False)
    op.create_index(op.f("ix_loans_status"), "loans", ["status"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column("deposit_alerts", sa.Boolean(), nullable=False),
        sa.Column("withdraw_alerts", sa.Boolean(), nullable=False),
        sa.Column("transfer_alerts", sa.Boolean(), nullable=False),
        sa.Column("interest_alerts", sa.Boolean(), nullable=False),
        sa.Column("loan_alerts", sa.Boolean(), nullable=False),
        sa.Column("admin_alerts", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_number"], ["accounts.account_number"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("account_number"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("notif_id", sa.String(length=24), nullable=False),
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("related_txn_id", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_number"], ["accounts.account_number"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notif_account_read", "notifications", ["account_number", "is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_account_number"), "notifications", ["account_number"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(op.f("ix_notifications_notif_id"), "notifications", ["notif_id"], unique=True)
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_table(
        "savings_goals",
        sa.Column("goal_id", sa.String(length=20), nullable=False),
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("target_date", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_number"], ["accounts.account_number"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("goal_id"),
    )
    op.create_index(
        op.f("ix_savings_goals_account_number"), "savings_goals", ["account_number"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("txn_id", sa.String(length=20), nullable=False),
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("target_account", sa.String(length=10), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_number"], ["accounts.account_number"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_txns_account_ts", "transactions", ["account_number", "timestamp"], unique=False
    )
    op.create_index("idx_txns_ts_type", "transactions", ["timestamp", "type"], unique=False)
    op.create_index(
        op.f("ix_transactions_account_number"), "transactions", ["account_number"], unique=False
    )
    op.create_index(op.f("ix_transactions_category"), "transactions", ["category"], unique=False)
    op.create_index(op.f("ix_transactions_timestamp"), "transactions", ["timestamp"], unique=False)
    op.create_index(op.f("ix_transactions_txn_id"), "transactions", ["txn_id"], unique=True)
    op.create_index(op.f("ix_transactions_type"), "transactions", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_txn_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_timestamp"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_number"), table_name="transactions")
    op.drop_index("idx_txns_ts_type", table_name="transactions")
    op.drop_index("idx_txns_account_ts", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_savings_goals_account_number"), table_name="savings_goals")
    op.drop_table("savings_goals")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notif_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_account_number"), table_name="notifications")
    op.drop_index("idx_notif_account_read", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_loans_status"), table_name="loans")
    op.drop_index(op.f("ix_loans_account_number"), table_name="loans")
    op.drop_index("idx_loans_status_next_emi", table_name="loans")
    op.drop_index("idx_loans_account_status", table_name="loans")
    op.drop_table("loans")
    op.drop_table("token_versions")
    op.drop_index(op.f("ix_login_attempts_key"), table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_admins_username"), table_name="admins")
    op.drop_table("admins")
    op.drop_index(op.f("ix_accounts_name"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_index("idx_accounts_status", table_name="accounts")
    op.drop_index("idx_accounts_name_number", table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
